#! /bin/sh

exec docker run \
	--read-only \
	--env NGINX_NO_LOGGING=Y \
	-v /opt/data/easy-nginx:/opt/data \
	-v /var/lib/pems:/opt/data/pems \
	-p 192.168.1.145:443:443 \
	-p 192.168.1.145:80:80 \
	-it easy-nginx $1
